services:
    ## CSV reader helper
    helper.csv_reader:
        class: AppBundle\Helper\CsvReader
        arguments: ['%csv_path%']

    ## Abstract resolver
    resolver.base:
        class: AppBundle\Resolver\AbstractResolver
        arguments: ['@helper.csv_reader']
        abstract: true

    ## Car api resolver
    resolver.car_api:
        class: AppBundle\Resolver\CarApiResolver
        parent: 'resolver.base'
